Repository SpaceyaTech/mastori, pull requests merged in 2022-12, with the labels that each got.

#58 Changing the site titles
  CMS/urls.py
Labels: enhancement

#61 Authentication Implementation
  .github/workflows/django.yml
  .gitignore
  CMS/settings.py
  CMS/tests/accounts/conftest.py
  CMS/tests/accounts/test_account_serializers.py
  CMS/tests/accounts/test_user_serializers.py
  CMS/urls.py
  README.md
  accounts/migrations/0004_alter_account_user.py
  accounts/migrations/0005_rename_name_account_account_name.py
  accounts/migrations/0006_alter_user_phone_number.py
  accounts/migrations/0007_alter_user_phone_number.py
  accounts/migrations/0008_alter_user_phone_number.py
  accounts/migrations/0009_alter_user_phone_number.py
  accounts/migrations/0010_alter_account_display_picture.py
  accounts/models.py
  accounts/serializers.py
  accounts/tests/test_models.py
  accounts/urls.py
  accounts/views.py
  pytest.ini
  requirements.txt
Labels: enhancement

#66 created blogposts models
  CMS/settings.py
  accounts/migrations/0004_alter_account_display_picture.py
  accounts/models.py
  blog/admin.py
  blog/migrations/0001_initial.py
  blog/models.py
  requirements.txt
Labels: In progress

#59 User-autentication
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/django.yml
  .gitignore
  CMS/settings.py
  CMS/urls.py
  README.md
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/permission.py
  accounts/serializer.py
  accounts/tests/__init__.py
  accounts/tests/test_models.py
  accounts/tests/test_serializers.py
  accounts/tests/test_views.py
  accounts/urls.py
  accounts/views.py
  blog/models.py
  blog/tests/__init__.py
  blog/tests/test_models.py
  blog/tests/test_serializers.py
  blog/tests/test_views.py
  contributions.md
  pull_request_template.md
  requirements.txt
Labels: enhancement, In progress
