Repository SpaceyaTech/mastori, pull requests merged in 2022-11, with the labels that each got.

#37 changing the account model from the blog app to account app
  CMS/settings.py
  accounts/admin.py
  accounts/migrations/0002_user_verification_code_account.py
  accounts/migrations/0003_alter_user_email.py
  accounts/models.py
  blog/admin.py
  blog/models.py
Labels: enhancement

#40 Unit tests of Account and User models
  accounts/tests.py
Labels: enhancement, good first issue

#41 Add unittests for user model
  CMS/settings.py
  accounts/__init__.py
  accounts/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_user_verification_code_account.py
  accounts/migrations/0003_alter_user_email.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/tests.py
  accounts/views.py
Labels: good first issue

#52 github templates
  .github/workflows/django.yml
  README.md
  pull_request_template.md
Labels: documentation
