Repository SpaceyaTech/mastori, pull requests merged in 2023-01, with the labels that each got.

#70 customized simple JWT token claims to enable token decoding on the frontend
  CMS/settings.py
  CMS/urls.py
  accounts/views.py
  requirements.txt
Labels: enhancement, In review

#73 Blog Template
  .github/.git_commit_template
  .github/workflows/django-postgres-ci.yml
  .github/workflows/django.yml
  CMS/settings.py
  CMS/urls.py
  README.md
  accounts/migrations/0011_merge_20230102_2059.py
  accounts/migrations/0012_merge_20230103_1021.py
  blog/admin.py
  blog/filters.py
  blog/migrations/0002_stori_delete_blogpost.py
  blog/models.py
  blog/serializers.py
  blog/urls.py
  blog/views.py
  requirements.txt
Labels: In progress, In review

#75 Contributions.md: Directions to create a virtual environment #74
  contributions.md
Labels: documentation

#79 Added a RichText ediror
  CMS/settings.py
  CMS/urls.py
  blog/migrations/0003_alter_stori_content.py
  blog/models.py
  requirements.txt
Labels: enhancement

#81 80 correct spacing
  contributions.md
Labels: documentation

#85 Create stale.yml
  .github/workflows/assign.yml
  .github/workflows/stale.yml
Labels: enhancement

#84 Auto fill slugfield from title
  blog/models.py
Labels: In review
